# name: SonarCloud Scan

# # Start the job on every push
# on:
#   push:
#     branches:
#       - "master"
#       - "main"
#       - "feature"

# # Set the job

# jobs:
#   sonarCloudTrigger:
#     name: SonarCloud Trigger
#     runs-on: ubuntu-latest
#     steps:
#       - name: Clone Repository
#         uses: actions/checkout@v2
#       - name: Analyze with SonarCloud
#         uses: sonarsource/sonarcloud-github-action@v1.3
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
# SECOND VERSION
name: SonarCloud Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Analyze with SonarCloud         
        # You can pin the exact commit or the version.
        # uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
        uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
        with:
          args:             
            -Dsonar.projectKey=HuusmannPablo_Mission-4
            -Dsonar.organization=huusmannpablo